# Generated by Django 6.0.3 on 2026-04-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('chapter_type', models.CharField(choices=[('theory', 'Теоретический материал'), ('test', 'Тест')], default='theory', max_length=20, verbose_name='Тип главы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('content', models.TextField(blank=True, verbose_name='Теоретический материал')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lmsapp.course', verbose_name='Курс')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option_a', models.CharField(max_length=500, verbose_name='Вариант А')),
                ('option_b', models.CharField(max_length=500, verbose_name='Вариант Б')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='Вариант В')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='Вариант Г')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'Б'), ('c', 'В'), ('d', 'Г')], max_length=1, verbose_name='Правильный ответ')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lmsapp.chapter', verbose_name='Глава')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('percent', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lmsapp.chapter', verbose_name='Глава')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_chapters', models.PositiveIntegerField(default=0, verbose_name='Пройдено глав')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='Всего глав')),
                ('percent_complete', models.FloatField(default=0, verbose_name='Процент прохождения курса')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Курс завершён')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения курса')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Последний доступ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lmsapp.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
