# Generated by Django 6.0.3 on 2026-04-27 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_chapter_question_testresult_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прочтения')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_progress', to='lmsapp.chapter', verbose_name='Глава')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
