# Generated by Django 6.0.3 on 2026-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комната чата'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
